version: "3.1"
services:
  nginx:
    image: nginx
    container_name: webserver
    depends_on:
      - php
    links:
      - php
    volumes:
      - ../site/:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log/error.log:/var/log/nginx/access.log
      - ./nginx/log/access.log:/var/log/nginx/error.log
    ports:
      - "8080:80"
    networks:
      static-network:
        ipv4_address: 134.0.0.5
  php:
    image: php:8.0-fpm
    build: ./php-fpm
    container_name: php2
    volumes:
      - ./php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ../site/:/var/www/html
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      static-network:
        ipv4_address: 134.0.0.6
  mysql:
    container_name: mysql2
    image: mysql:8.0
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      static-network:
        ipv4_address: 134.0.0.3
networks:
  static-network:
    ipam:
      config:
        - subnet: 134.0.0.0/16
